### ISSUE TITLE
Having trouble getting ecerything to initialize

### ISSUE THREAD

**Issue by urakkaamyx** [jenheilemann/bitburner-scripts#2]
i setup the aliases, and when i try to do `get player` , or `get "player" ` it always comes up null. 

technically thats not my issue, but rather when trying to run `best` i get a error``

```
RUNTIME ERROR
bestHack.js@home

Cannot read properties of undefined (reading 'hacking')
stack:
TypeError: Cannot read properties of undefined (reading 'hacking')
at bestHack.js:62:55
at Array.filter ()
at BestHack.scoreAndFilterServers (bestHack.js:62:8)
at BestHack.findBestPerLevel (bestHack.js:32:25)
at Module.main (bestHack.js:84:29)
```

i ran the networkMap file and it did generate the `jh_network_map` in local storage with all the servers afaik. it also generated a `network_map.txt`

**Comment by urakkaamyx** [comment]
nevermind, i need sourcefile 4-1 and run playerObserver.js

**Comment by jenheilemann** [comment]
Most of the aliases and commands won't really work unless you've run the startup script and have `satellites/controller.js` running. As the README says, this repo isn't really backwards compatible for a new player. Maybe someday it will be, but it's pretty much following my own abilities as I play the game. Good luck with the game!
